apiVersion: apps/v1
kind: Deployment
metadata:
  name: regapp
  labels:
    app: regapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: regapp
  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp
        image: 184235429893.dkr.ecr.us-west-1.amazonaws.com/dockerregistry
        ports:
        - containerPort: 8080
